global:
  smtp_smarthost: "sandbox.smtp.mailtrap.io:587"
  smtp_from: "alerts@captioningapp.local"
  smtp_auth_username: "29b3b29e56b9f7"
  smtp_auth_password: "6b457a1ea87854"
  smtp_require_tls: false

route:
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "mailtrap_inbox"

  routes:
    - match:
        severity: critical
      receiver: "mailtrap_inbox"
      group_wait: 10s

receivers:
  - name: "mailtrap_inbox"
    email_configs:
      - to: "test@example.com"
        send_resolved: true
        headers:
          Subject: "[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}"

inhibit_rules:
  - source_match:
      alertname: "AppDown"
    target_match:
      alertname: "SlowInference"
    equal: ["instance"]
